# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mkdev < Formula
  desc "Trusted HTTPS dev server with LAN broadcast via mDNS"
  homepage "https://github.com/venkatkrishna07/mkdev"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/venkatkrishna07/mkdev/releases/download/v0.3.0/mkdev_0.3.0_darwin_amd64.tar.gz"
      sha256 "27f79e586172cc9b97cbdea0b4da7da35bcbdd8563b07eaa8699dd6f904eb628"

      define_method(:install) do
        bin.install "mkdev"
        generate_completions_from_executable(bin/"mkdev", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/venkatkrishna07/mkdev/releases/download/v0.3.0/mkdev_0.3.0_darwin_arm64.tar.gz"
      sha256 "5481cf9e793f9b415a3798a8011c80ef9a459bb350e1fcef7e2ca41f2fd1c85c"

      define_method(:install) do
        bin.install "mkdev"
        generate_completions_from_executable(bin/"mkdev", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/venkatkrishna07/mkdev/releases/download/v0.3.0/mkdev_0.3.0_linux_amd64.tar.gz"
      sha256 "a91e4e6e69a120aa178db99d455cc19b3d3d29751c83bebc7f5b0de7188420b9"
      define_method(:install) do
        bin.install "mkdev"
        generate_completions_from_executable(bin/"mkdev", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/venkatkrishna07/mkdev/releases/download/v0.3.0/mkdev_0.3.0_linux_arm64.tar.gz"
      sha256 "9a9f414b2628c586ec66814bedc2c6f1d5353f4d10a1d14c00594bf790319865"
      define_method(:install) do
        bin.install "mkdev"
        generate_completions_from_executable(bin/"mkdev", "completion")
      end
    end
  end

  test do
    system "#{bin}/mkdev", "--version"
  end
end
