# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mkdev < Formula
  desc "Trusted HTTPS dev server with LAN broadcast via mDNS"
  homepage "https://github.com/venkatkrishna07/mkdev"
  version "0.0.1-test"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/venkatkrishna07/mkdev/releases/download/v0.0.1-test/mkdev_0.0.1-test_darwin_amd64.tar.gz"
      sha256 "0c32d846ab7b2da7fd8a00e1fe0ea9bb3bc621df1290000c7dfd3fd70e1929cb"

      define_method(:install) do
        bin.install "mkdev"
        generate_completions_from_executable(bin/"mkdev", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/venkatkrishna07/mkdev/releases/download/v0.0.1-test/mkdev_0.0.1-test_darwin_arm64.tar.gz"
      sha256 "001acfd2b0ac0930c7db6784862880d630513bf0f18d7c7b4e0d18c3d3837afe"

      define_method(:install) do
        bin.install "mkdev"
        generate_completions_from_executable(bin/"mkdev", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/venkatkrishna07/mkdev/releases/download/v0.0.1-test/mkdev_0.0.1-test_linux_amd64.tar.gz"
      sha256 "00c0932963a91323bd7740301f942c1b2d9d27545c8bcad9e53ee890ad49b371"
      define_method(:install) do
        bin.install "mkdev"
        generate_completions_from_executable(bin/"mkdev", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/venkatkrishna07/mkdev/releases/download/v0.0.1-test/mkdev_0.0.1-test_linux_arm64.tar.gz"
      sha256 "8bda84bcf111552e390bab6504a4050e3c642ca3b3f9cf752a139d85c2789084"
      define_method(:install) do
        bin.install "mkdev"
        generate_completions_from_executable(bin/"mkdev", "completion")
      end
    end
  end

  test do
    system "#{bin}/mkdev", "--version"
  end
end
